version: '3.0'

services:
  myeurekaserver:
    container_name: myeurekaserver
    build:
      context: ./MyEurekaServer
      dockerfile: Dockerfile
    ports:
    -  "8761:8761"
  
  myeurekajpa:
    container_name: myeurekajpa
    build:
      context: ./MyEurekaJpa
      dockerfile: Dockerfile
    environment:
    - eureka.client.service-url.defaultZone=http://myeurekaserver:8761/eureka/
    - eureka.instance.prefer-ip-address=true
    - spring.datasource.url=jdbc:mysql://mydatabase.crmstchzv6s3.ap-south-1.rds.amazonaws.com:3306/mydatabase
    - spring.datasource.username=root
    - spring.datasource.password=rootroot

    
    depends_on:
    - myeurekaserver  
    ports:
    - "8085:8085"
  
  myeurekaclient:
    container_name: myeurekaclient
    build:
      context: ./MyEurekaClient
      dockerfile: Dockerfile
    environment:
    - eureka.client.service-url.defaultZone=http://myeurekaserver:8761/eureka/
    - eureka.instance.prefer-ip-address=true
    depends_on:
    - myeurekaserver
    - myeurekajpa
    ports:
    - "8086:8086"

  myauth:
    container_name: myauth
    build:
      context: ./MyAuth
      dockerfile: Dockerfile
    environment:
    - eureka.client.service-url.defaultZone=http://myeurekaserver:8761/eureka/
    - eureka.instance.prefer-ip-address=true
    - spring.datasource.url=jdbc:mysql://mydatabase.crmstchzv6s3.ap-south-1.rds.amazonaws.com:3306/mydatabase
    - spring.datasource.username=root
    - spring.datasource.password=rootroot
    depends_on:
    - myeurekaserver
    ports:
    - "8090:8090"

  mygateway:
    container_name: mygateway
    build:
      context: ./MyGatewayService
      dockerfile: Dockerfile
    environment:
    - eureka.client.service-url.defaultZone=http://myeurekaserver:8761/eureka/
    - eureka.instance.prefer-ip-address=true
    - spring.cloud.gateway.routes[0].id=MYEUREKACLIENT
    - spring.cloud.gateway.routes[0].uri=lb://MYEUREKACLIENT
    - spring.cloud.gateway.routes[0].predicates[0]=Path=/getEmp/**
    
    - spring.cloud.gateway.routes[1].id=MYAUTH
    - spring.cloud.gateway.routes[1].uri=lb://MYAUTH
    - spring.cloud.gateway.routes[1].predicates[0]=Path=/authenticate/**
  
    - spring.cloud.gateway.routes[1].predicates[1]=Path=/validate/**
    
    
    ports:
    - "8087:8087"
    depends_on:
    - myeurekaserver
    - myauth
    - myeurekaclient  

  